### PR TITLE
Fix setup.py

### PR DESCRIPTION
**Pull request by syed**
Installs the module correctly

### CODE REVIEW

**Comment by j-griffith** [comment]
LGTM Syed, thanks for the patch!  I'll let folks take a closer look at Travis and get this merged.

**Comment by syed** [comment]
@j-griffith Thanks. FYI although this patch fixes the install issue, I've been having trouble getting the SDK to work. For now I've written a thin wrapper around the JSON-RPC that is exposed by SolidFire and using that to continue my work.

**Comment by j-griffith** [comment]
@syed, hmm... if you get a chance open an issue with some details, I'll make sure we forward on to the gen team and get things squared away for ya!!

**Comment by syed** [comment]
Thanks @j-griffith I've opened #3 with all the info. If you need more info, please feel free to reach out

**Comment by jason-womack** [comment]
We have not fully release our SDK yet.  All of the model and service specific code has not been checked in yet...

**Pull request closed without merging**
